export const trainers = {
  state: {
    filterValue: 'Trainer',
    allTrainers: [
       {
          id: 1,
          img: require("../assets/img/all-trainers/trainer-1.jpg"),
          flag: require("../assets/img/icons/flags/austria.png"),
          name: "Lisa Zöchner",
          country: "Austria",
          city: "Graz, Leibnitz, Wien",
          category: "...",
          type: "Dietitian",
          rating: "4.5",
          liveTraining: false,
          cost: "$15",
          liked: true,
           pro: true,
        },
        {
          id: 2,
          img: require("../assets/img/all-trainers/trainer-2.jpg"),
          flag: require("../assets/img/icons/flags/austria.png"),
          name: "Behar Gashi",
          country: "Austria",
          city: "Schwechat",
          category: "Muay Thai",
          type: "Trainer",
          rating: "4.9",
          liveTraining: false,
          cost: "$10",
          liked: true,
           pro: false,
        },
        {
          id: 3,
          img: require("../assets/img/all-trainers/trainer-3.jpg"),
          flag: require("../assets/img/icons/flags/india.png"),
          name: "Tawhid hossain",
          country: "India",
          city: "kolkata",
          category: "Fitness",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$5",
          liked: true,
           pro: true,
        },
        {
          id: 4,
          img: require("../assets/img/all-trainers/trainer-4.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Yoga",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: false,
        },
        {
          id: 5,
          img: require("../assets/img/all-trainers/trainer-5.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Moravcik Vladimir",
          country: "Slovakia",
          city: "Banska Bystrica",
          category: "Muay Thai",
          type: "Dietitian",
          rating: "4.9",
          liveTraining: true,
          cost: "$150",
          liked: false,
           pro: true,
        },
        {
          id: 6,
          img: require("../assets/img/all-trainers/trainer-6.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Moravcik Vladimir",
          country: "Slovakia",
          city: "Bratislava",
          category: "Conditioning Trainer",
          type: "Dietitian",
          rating: "4.9",
          liveTraining: true,
          cost: "$150",
          liked: false,
           pro: false,
        },
        {
          id: 7,
          img: require("../assets/img/all-trainers/trainer-7.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Moravcik Vladimir",
          country: "Slovakia",
          city: "Bratislava",
          category: "Conditioning Trainer",
          type: "Dietitian",
          rating: "4.9",
          liveTraining: false,
          cost: "$150",
          liked: false,
           pro: false,
      },
        {
          id: 8,
          img: require("../assets/img/all-trainers/trainer-8.jpg"),
          flag: require("../assets/img/icons/flags/india.png"),
          name: "Tawhid hossain",
          country: "India",
          city: "kolkata",
          category: "Fitness",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$5",
          liked: true,
           pro: true,
        },
        {
          id: 9,
          img: require("../assets/img/all-trainers/trainer-9.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Yoga",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: true,
        },
        {
          id: 10,
          img: require("../assets/img/all-trainers/trainer-10.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Yoga",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: true,
        },
        {
          id: 11,
          img: require("../assets/img/all-trainers/trainer-11.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Fitness",
          type: "Trainer",
          rating: "4.8",
          liveTraining: false,
          cost: "$30",
          liked: false,
           pro: true,
        },
        {
          id: 12,
          img: require("../assets/img/all-trainers/trainer-12.png"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Grappling",
          type: "Trainer",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: true,
      },
        // extra
        {
          id: 13,
          img: require("../assets/img/all-trainers/trainer-7.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Moravcik Vladimir",
          country: "Slovakia",
          city: "Bratislava",
          category: "Conditioning Trainer",
          type: "Trainer",
          rating: "4.9",
          liveTraining: false,
          cost: "$150",
          liked: false,
           pro: false,
      },
        {
          id: 14,
          img: require("../assets/img/all-trainers/trainer-8.jpg"),
          flag: require("../assets/img/icons/flags/india.png"),
          name: "Tawhid hossain",
          country: "India",
          city: "kolkata",
          category: "Fitness",
          type: "Dietitian",
          rating: "4.8",
          liveTraining: true,
          cost: "$5",
          liked: true,
           pro: true,
        },
        {
          id: 15,
          img: require("../assets/img/all-trainers/trainer-9.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Yoga",
          type: "Dietitian",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: true,
      },
        {
          id: 16,
          img: require("../assets/img/all-trainers/trainer-2.jpg"),
          flag: require("../assets/img/icons/flags/austria.png"),
          name: "Behar Gashi",
          country: "Austria",
          city: "Schwechat",
          category: "Muay Thai",
          type: "Dietitian",
          rating: "4.9",
          liveTraining: false,
          cost: "$10",
          liked: true,
           pro: false,
        },
        {
          id: 17,
          img: require("../assets/img/all-trainers/trainer-3.jpg"),
          flag: require("../assets/img/icons/flags/india.png"),
          name: "Tawhid hossain",
          country: "India",
          city: "kolkata",
          category: "Fitness",
          type: "Dietitian",
          rating: "4.8",
          liveTraining: true,
          cost: "$5",
          liked: true,
           pro: true,
        },
        {
          id: 18,
          img: require("../assets/img/all-trainers/trainer-4.jpg"),
          flag: require("../assets/img/icons/flags/slovakia.png"),
          name: "Vierka Ayisi",
          country: "Slovakia",
          city: "Bratislava",
          category: "Yoga",
          type: "Dietitian",
          rating: "4.8",
          liveTraining: true,
          cost: "$30",
          liked: false,
           pro: false,
        },
    ]
  },
  mutations: {
    // setTreaners(state, payload) {
    //   state.allTrainers = payload
    // }

  },
  actions: {
    // setTreaners({ commit }, payload) {
    //     commit("setTreaners", payload)
    // }
  },
  getters: {
    getTrainers(state) {
      return state.allTrainers.filter((trainer) => trainer.type === state.filterValue)
    },
    getDietitians(state) {
      return state.allTrainers.filter((trainer) => trainer.type === "Dietitian")
    },
    getLiked(state) {
      return state.allTrainers.filter((trainer) => trainer.liked)
    },
    getProTrainers(state) {
      return state.allTrainers.filter((trainer) => trainer.pro &&  trainer.type === state.filterValue)
    },
    getProDietitians(state) {
      return state.allTrainers.filter((trainer) => trainer.pro &&  trainer.type === "Dietitian")
    },
    getLifeTrainers(state) {
      return state.allTrainers.filter((trainer) => trainer.liveTraining &&  trainer.type === state.filterValue)
    },
    getLifeDietitians(state) {
      return state.allTrainers.filter((trainer) => trainer.liveTraining &&  trainer.type ===  "Dietitian")
    },
    getPros(state) {
      return state.allTrainers.filter((trainer) => trainer.pro)
    },
    getSingleTrainer: (state) => (id) =>  {
      return state.allTrainers.find((t) => +t.id === +id);
    }
  }
}